name: laravel_exception
description: parse laravel exceptions to dart classes for easier and better handling support 422 - validation ,500 server errors , 404 not found exceptions
version: 0.0.3
homepage: https://github.com/maxzod/laravel_exception
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  blueprint: ^0.0.1-beta
  equatable: ^2.0.3

dev_dependencies:
  lints: ^1.0.1
  test: ^1.16.0
