name: laravel_exception
description: parse laravel exception message to dart class with geters to make it simpler
version: 0.0.1-beta
homepage: https://github.com/maxzod/
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  meta: ^1.7.0

dev_dependencies:
  lint: ^1.5.3
  test: ^1.16.0
